
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Items
{

    public int Item_ID { get; set; }

    public string Title { get; set; }

    public string Image { get; set; }

    public Nullable<decimal> Cost { get; set; }

    public int TenantId { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public Nullable<System.DateTime> DeletedDate { get; set; }

    public bool IsActive { get; set; }

    public string Comment { get; set; }

    public int CategoryId { get; set; }

    public int Qty { get; set; }

    public int ReOrderLevel { get; set; }

}

}
