
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tenant
{

    public int TenantId { get; set; }

    public string Name { get; set; }

    public string TradingAs { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public Nullable<System.DateTime> DeletedDate { get; set; }

    public bool IsActive { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string VatNumber { get; set; }

    public string VatRegister { get; set; }

}

}
