
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Transaction
{

    public int TransactionId { get; set; }

    public int CustomerId { get; set; }

    public int Userid { get; set; }

    public System.DateTime TransactionDate { get; set; }

    public Nullable<System.DateTime> RequiredDate { get; set; }

    public Nullable<System.DateTime> ShippedDate { get; set; }

}

}
