
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public int User_ID { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public int TenantId { get; set; }

    public bool IsActive { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public Nullable<System.DateTime> DeletedDate { get; set; }

    public string Password { get; set; }

}

}
